- name: loading platform variables
  include_vars: "{{ ansible_os_family|lower }}.yml"
  tags:
    - php

#Installing REPO for Debian
- name: adding deb.sury.org GPG key
  apt_key: 
    url=https://packages.sury.org/php/apt.gpg 
    state=present
  when: ansible_distribution == "Debian"
  tags:
    - php

- name: installing PHP deb.sury.org repository
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
  when: ansible_distribution == "Debian"
  tags:
    - php

#Installing REPO for Ubuntu
- name: installing PHP PPA via apt-repository
  apt_repository: 
    repo: ppa:ondrej/php 
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  tags:
    - php

#Installing packages via apt
- name: installing common packages via apt
  apt: 
    name={{ item }}
    install_recommends=no
    state=present
  with_items: '{{php_role.common.packages}}'
  when: ansible_os_family == "Debian"
  tags:
    - php

- name: installing PHP extensions via apt
  apt: 
    name={{ item }}
    install_recommends=no
    state=present
  with_items: '{{php_role.extensions.packages}}'
  when: ansible_os_family == "Debian"
  tags:
    - php

#installing common packages via yum    
- name: installing common packages via yum
  yum: 
    name={{ item }} 
    state=present 
    enablerepo=remi,remi-php56
  with_items: '{{php_role.common.packages}}'
  when: ansible_os_family == "RedHat"
  tags:
    - php

- name: installing PHP extensions via yum
  yum: 
    name={{ item }} 
    state=present 
    enablerepo=remi,remi-php56
  with_items: '{{php_role.extensions.packages}}'
  when: ansible_os_family == "RedHat"
  tags:
    - php

#Preparating configurations 
# PHP.ini
- name: copying default configurations
  template: 
    src={{ item.src }}.j2 
    dest=/etc/{{ item.dest }}
  with_items:
    - { src: "php.ini", dest: "php.ini" }
  tags:
    - php

- name: removing CLI configuration
  file:
    path=/etc/php/5.6/cli/php.ini
    state=absent
  register: php_result
  when: ansible_os_family == "Debian"
  tags:
    - nginx

- name: enabling CLI configuration
  file:
    src=/etc/php.ini
    dest=/etc/php/5.6/cli/php.ini
    state=link
  when: (ansible_os_family == "Debian") and (php_result is changed)
  tags:
    - nginx

#APCU
- name: copying APCu configuration on Debian/Ubuntu
  template: 
    src={{ item.src }}.j2 
    dest=/etc/php/5.6/mods-available/{{ item.dest }}
  with_items:
    - { src: "extensions/apcu.ini", dest: "apcu.ini" }
  when: ansible_os_family == "Debian"
  tags:
    - php

- name: copying APCu configuration on RHEL/CentOS
  template: 
    src={{ item.src }}.j2 
    dest=/etc/php.d/{{ item.dest }}
  with_items:
    - { src: "extensions/apcu.ini", dest: "40-apcu.ini" }
  when: ansible_os_family == "RedHat"
  tags:
    - php

#REDIS
- name: copying Redis configuration on Debian/Ubuntu
  template: 
    src={{ item.src }}.j2 
    dest=/etc/php/5.6/{{ item.dest }}
  with_items:
    - { src: "extensions/redis.ini", dest: "mods-available/redis.ini" }
  when: ansible_os_family == "Debian"
  tags:
    - php

- name: copying Redis configuration on RHEL/CentOS
  template: 
    src={{ item.src }}.j2 
    dest=/etc/php.d/{{ item.dest }}
  with_items:
    - { src: "extensions/redis.ini", dest: "50-redis.ini" }
  when: ansible_os_family == "RedHat"
  tags:
    - php